HIITMEMARIO/StudyClass

- mjh/2024-02-29.md
https://velog.io/@alswnsgur119/Next.js%EC%9D%98-%EB%A0%8C%EB%8D%94%EB%A7%81-%EB%B0%A9%EC%8B%9D
> [민준혁] 넥스트의 렌더링방식

- scs/2024-02-29.md
리액트 클린코드 상태와 관련한 내용 정리 
불필요한 상태를 만들게 되면 리액트에 의해 관리되는 값이 늘어나 렌더링에도 영향을 준다. 예를 들어 살펴보자. 투두리스트에서 완료된 항목만 화면에 나타내고자 한다.
```jsx
import { useEffect, useState } from 'react';
function DoneTodoList({ todos }) {
const [todoList, setTodoList] = useState(todos);
const doneList = todos.filter((todo) => todo.completed);
return (
<ul>
{doneList.map((todo) => (
<li key={todo.id}>
{todo.title} - {todo.description}
</li>
))}
</ul>
);
}
```
`doneList`는 `todos`로부터 계산할 수 있다. 굳이 상태로 관리할 필요 없이 컴포넌트 내부에서 계산된 값을 사용하여 렌더링하면 된다. 컴포넌트 내부의 변수는 렌더링마다 고유의 계산된 값을 가진다.
게다가 `todos` prop이 상위 컴포넌트로부터 업데이트될 경우, 리액트는 자동으로 컴포넌트를 새로운 props와 함께 리렌더링한다. 따라서 `useState`를 통해 상태를 만들 필요가 없다.
상태 관리나 사이드 이펙트 로직 없이 props를 바로 사용하기 때문에 코드가 훨씬 간결하고 명확하다. 
```jsx
function DoneTodoList({ todos }) {
const doneList = todos.filter((todo) => …
```
> [손창성] 리액트 클린코드: State (2)

- jms/2024-02-29.md
https://velog.io/@minseok0920/%EC%BB%A4%EC%8A%A4%ED%85%80-%ED%9B%85
> [전민석] 커스텀 훅 학습

- lhw/2024-02-29.md
> [임홍원] 프로젝트 무한스크롤 구현 및 알고리즘

- yhw/2024-02-29.md
keyboduck 프로젝트 코드 개선 2
블로그 주소
[keyboduck 프로젝트 코드 개선 2](https://zheldqodnsmstkfka.tistory.com/94)
> [염혜원] keyboduck 프로젝트 코드 개선 2

- mjh/2024-03-04.md
https://velog.io/@alswnsgur119/keyboduck-%ED%94%84%EB%A1%9C%EC%A0%9D%ED%8A%B8-%EB%A6%AC%ED%8C%A9%ED%86%A0%EB%A7%81
https://github.com/4anghyeon/keyboduck
> [민준혁] keyboduck 프로젝트 리펙토링

- yhw/2024-03-04.md
- 커리어톤 참여
- 이력서 수정
- Javascript 기초 복습
- TIL 주소 : <https://zheldqodnsmstkfka.tistory.com/95>
> [염혜원] 이력서 수정 및 JS 기초 복습

- yhw/2024-03-05.md
- 커리어톤 참여
- 이력서 수정 및 지원전략 수립
- 인텔리픽 이력서 코칭 신청
- Javascript 기초 복습 2
[블로그 주소](https://zheldqodnsmstkfka.tistory.com/96)
> [염혜원] 커리어톤 참여 및 JS기초 복습

- scs/2024-03-05.md
> Traditionally when creating web pages, web developers marked up their content and then added interaction by sprinkling on some JavaScript. This worked great when interaction was a nice-to-have on the web. Now it is expected for many sites and all apps. React puts interactivity first while still using the same technology: **a React component is a JavaScript function that you can \*sprinkle with markup\*.** [[Defining a component ](https://react.dev/learn/your-first-component#defining-a-component)](https://react.dev/learn/your-first-component#defining-a-component) 
기존에 웹 페이지를 만들 때는 웹 개발자가 HTML 마크업을 한 다음 자바스크립트를 입히는 방식으로 상호작용을 추가했다. 이 방식은 웹에서 상호작용이 부가적인 기능이었을 때는 잘 작동했다. 이제는 많은 사이트와 모든 애플리케이션에서 사용자의 수많은 상호작용을 다루고 응답하여 보여준다. 
React 컴포넌트는 마크업을 적절히 포함할 수 있는 자바스크립트 함수이다. JSX 문법을 사용하여 HTML과 유사한 …
> [손창성] 리액트 클린코드: Components

- jms/2024-03-05.md
https://velog.io/@minseok0920/this
> [전민석] this

- yhw/2024-03-06.md
- 커리어톤 참여
- 가족 행사로 불참
- [펜레터 프로젝트 리팩토링](https://zheldqodnsmstkfka.tistory.com/97)
> [염혜원] FanLetter 코드개선

- jms/2024-03-06.md
https://velog.io/@minseok0920/%EC%BD%9C%EB%B0%B1-%ED%95%A8%EC%88%98
> [전민석]콜백 함수

- scs/2024-03-06.md
0은 자바스크립트에서 falsy한 값으로 평가된다. 이로 인해 리액트 조건부 렌더링에서도 0을 falsy한 값으로 다음과 같이 사용하기도 한다.
```jsx
function Component() {
const [messageCount, setMessageCount] = useState(0);
return <>{messageCount && <p>New messages</p>}</>;
}
```
`items.length`가 0 일 때 아무것도 렌더링하지 않을 것이라 기대하지만, **실제로는 0 자체를 렌더링한다.** JSX 에서 0은 유효한 값으로 평가하여 렌더링의 대상으로 간주한다. 조건부로 렌더링할 때는 `messageCount > 0 && <p>New messages</p>}</>`과 같이 좌항을 Boolean 값으로 만들도록 하자.
리액트에서는 `Warning: Each child in a list should have a unique 'key' prop`라는 경고 메시지를 종종 볼 수 있다. 이는 리스트를 렌더링할 때 각 리스트 아이템에 고유한 key를 부여하지 않았기 때문이다. 
```jsx
function Component({ items }) {
return (
<>
{items.map((item) => (
<div>{item}</div>
))}
</>
)  
}
```
비슷하게 생긴 여러 개의 아이템들이 렌더링되고 추가, 변경, 제거될 때 아이템을 구별할 수 있는 무언가가 필요하다. key가 바로 그러한 역할이다.
key는 동적인 리스트에서 어떤 항목들이 변경되었는지 식별할 수 있도록 도와준다. …
> [손창성] 리액트 클린코드: Rendering

- lhw/2024-03-06.md
1. 네이버 & 토스 지원완료
2. 자바스크립트 중급 이론 공부
3. 면접 준비
4. LeetCode 알고리즘 문제 풀기 (https://velog.io/@h0ngwon/LeetCode-Javascript-1679.-Max-Number-of-K-Sum-Pairs)
> [임홍원] 네이버 지원 + 알고리즘 + 면접준비

- yhw/2024-03-07.md
- 커리어톤 참여
- 예상 면접 질문 작성
- 이력서 1곳 지원
- 자기소개서 작성 중
- [Supabase](https://zheldqodnsmstkfka.tistory.com/98)
> [염혜원] 커리어톤 및 Supabase

- lhw/2024-03-07.md
1. 코딩테스트 준비
2. LeetCode 643 (https://velog.io/@h0ngwon/LeetCode-Javascript-643.-Maximum-Average-Subarray-I)
3. 자바스크립트 공부
4. 다음주 면접 준비
> [임홍원] 면접준비 및 알고리즘

- mjh/2024-03-07.md
https://velog.io/@alswnsgur119/%EC%9E%90%EB%A3%8C%EA%B5%AC%EC%A1%B0-%ED%81%90
+ 이력서 수정
> [민준혁] 자료구조 큐

- lyj/2024-03-07.md
https://velog.io/@yeahzzl/%EC%BF%A0%ED%82%A4-%EC%84%B8%EC%85%98-%EC%9B%B9%EC%8A%A4%ED%86%A0%EB%A6%AC%EC%A7%80
> [이예지] 쿠키, 세션, 웹 스토리지에 대해 정리

- jms/2024-03-07.md
https://velog.io/@minseok0920/%ED%94%84%EB%A1%9C%ED%86%A0%ED%83%80%EC%9E%85
> [전민석] 프로토타입

- yhw/2024-03-08.md
- 커리어톤 참여
- [React, 실제 DOM과 가상 DOM](https://zheldqodnsmstkfka.tistory.com/99)
> [염혜원] React, 실제 DOM과 가상 DOM

- mjh/2024-03-08.md
https://velog.io/@alswnsgur119/%EC%8A%A4%ED%83%9D
> [민준혁] 자료구조 스택

- jms/2024-03-08.md
https://velog.io/@minseok0920/%ED%94%84%EB%A1%9C%ED%86%A0%ED%83%80%EC%9E%85-2
> [전민석] 프로토타입 2

- lyj/2024-03-08.md
https://velog.io/@yeahzzl/%EA%B8%B0%EC%88%A0%EB%A9%B4%EC%A0%91-part.3
> [이예지] Next.js 렌더링 3가지 정리

- jms/2024-03-11.md
https://velog.io/@minseok0920/Monorepo
> [전민석] 모노리포

- mjh/2024-03-11.md
https://velog.io/@alswnsgur119/CDN
> [민준혁] CDN의 개념

- yhw/2024-03-11.md
- 커리어톤 참여
- [자료구조 - 배열(Array)](https://zheldqodnsmstkfka.tistory.com/100)
> [염혜원] 커리어톤 참여 및 자료구조(배열)

- lyj/2024-03-11.md
[블로그링크](https://velog.io/@yeahzzl/TCP-vs-UDP-http-vs-https-%EB%9D%BC%EC%9D%B4%ED%94%84%EC%82%AC%EC%9D%B4%ED%81%B4)
> [이예지] TCP & UDP 알아보기

- mjh/2024-03-12.md
https://velog.io/@alswnsgur119/DNS
> [민준혁] DNS의 개념

- yhw/2024-03-12.md
- 커리어톤 참여
- 면접준비
- [자료구조 - 스택(Stack)](https://zheldqodnsmstkfka.tistory.com/101)
> [염혜원] 자료구조 - 스택

- jms/2024-03-12.md
https://velog.io/@minseok0920/Headless-component
> [전민석] Headless component

- lhw/2024-03-13.md
1. https://velog.io/@h0ngwon/PNPM-Vite-TypeScript-%EC%A0%81%EC%9A%A9%ED%95%98%EA%B8%B0
2. 메라키플레이스 과제
> [임홍원] PNPM + React + Vite + Typescript

- yhw/2024-03-13.md
- 커리어톤 참여
- 모의면접
- 자료구조 - 큐(Queue)
- TIL 주소 : <https://zheldqodnsmstkfka.tistory.com/102>
> [염혜원] 자료구조 큐(Queue)

- mjh/2024-03-13.md
https://velog.io/@alswnsgur119/%EC%9D%B4%EB%B2%A4%ED%8A%B8-%EB%A3%A8%ED%94%84
> [민준혁] 이벤트 루프의 개념

- jms/2024-03-13.md
https://velog.io/@minseok0920/%EC%BB%B4%ED%8C%8C%EC%9A%B4%EB%93%9C-%ED%8C%A8%ED%84%B4
> [전민석] Compound pattern

- mjh/2024-03-14.md
https://velog.io/@alswnsgur119/%ED%9E%99
> [민준혁] 자료구조 힙

- yhw/2024-03-14.md
- 커리어톤 참여
- [자료구조 - 큐(Queue)](https://zheldqodnsmstkfka.tistory.com/103)
> [염혜원] 자료구조 - 트리(Tree)

- jms/2024-03-14.md
https://velog.io/@minseok0920/%EC%95%8C%EA%B3%A0%EB%A6%AC%EC%A6%98-gf9fes2m
> [전민석] 알고리즘

- lyj/2024-03-14.md
[블로그링크](https://velog.io/@yeahzzl/http-vs-https)
> [이예지] 이론정리 http vs https 등등

- mjh/2024-03-15.md
https://velog.io/@alswnsgur119/%ED%98%B8%EC%9D%B4%EC%8A%A4%ED%8C%85
> [민준혁] 호이스팅 탐구

- yhw/2024-03-15.md
- 커리어톤 참여
- [자료구조 - 그래프(Graph)](https://zheldqodnsmstkfka.tistory.com/104)
> [염혜원] 자료구조 - 그래프(Graph)

- lyj/2024-03-15.md
[블로그링크](https://velog.io/@yeahzzl/React%EC%9D%98-Life-Cycle)
+) 추가
- 어제 올렸던 링크 제가 비공개로 해놓고 올려서 안보였었나봐요ㅠ 바로 수정했습니다
> [이예지] React 라이프사이클 알아보기

- jms/2024-03-15.md
https://velog.io/@minseok0920/%EC%BD%94%EB%94%A9%EC%BB%A8%EB%B2%A4%EC%85%98-%EB%A6%AC%EB%93%9C%EB%AF%B8
> [전민석] 코딩컨벤션 & 리드미

- mjh/2024-03-18.md
https://velog.io/@alswnsgur119/zod
> [민준혁] zod 라이브러리 

- yhw/2024-03-18.md
- 데브캠프 참여
- shadcn/ui, zod, react-hook-form 라이브러리 공부
- [회원가입 구현하기(UI 편)](https://zheldqodnsmstkfka.tistory.com/105)
> [염혜원] 회원가입 페이지 구현하기 (UI편)

- scs/2024-03-18.md
React Router는 React로 만들어진 웹 애플리케이션에서 클라이언트 측 라우팅을 구현하기 위한 라이브러리이다. 라우팅이란 웹 사이트 어느 주소(URL)에 접근했을 때 그에 맞는 적절한 화면을 보여주는 기능이다.
클라이언트 측 라우팅은 **페이지 전환을 브라우저에서 처리하는 방식**이다. 기존의 전통적인 서버 측 라우팅은 사용자가 어떤 페이지에 접근하면 URL에 해당하는 페이지의 전체 HTML을 새로 생성하여 전송한다. 사용자가 다른 페이지로 이동할 때마다 새로운 요청이 서버로 전송되고, 브라우저는 서버로부터 응답받아 새 HTML로 전체 페이지를 다시 로드한다.
그러나 싱글 페이지 애플리케이션(SPA)에서는 새로운 페이지의 요청을 서버에 보내 전체 페이지를 새로 불러오는 대신 필요한 데이터만 서버로부터 비동기적으로 가져와서 현재 페이지를 업데이트한다. 
> [클라이언트 측 라우팅과 서버 측 라우팅 비교](https://ko.vuejs.org/guide/scaling-up/routing#client-side-vs-server-side-routing)
React Router는 웹(React Router Dom)뿐 아니라 모바일 앱(React Router Native)을 위한 라우팅 기능을 제공하는 반면, React Router Dom은 웹 애플리케이션용으로 특별히 설계된 React Router의 확장 라이브러리이다.
> [React Router Vs React Router DOM](https://www.linkedin.com/pulse/react-router-vs-dom-aysanew-yonas-b2xje …
> [손창성] React Router

- jms/2024-03-18.md
https://velog.io/@minseok0920/%EC%A0%95%EA%B7%9C%ED%91%9C%ED%98%84%EC%8B%9D
> [전민석]정규표현식

- mjh/2024-03-19.md
https://velog.io/@alswnsgur119/%EC%BD%94%EB%93%9C-%EC%8A%A4%ED%94%8C%EB%A6%AC%ED%8C%85
> [민준혁] 코드 스플리팅의 개념

- yhw/2024-03-19.md
- 데브캠프 참여
- shadcn/ui, zod, react-hook-form 라이브러리 공부
- [회원가입 구현하기(2편)](https://zheldqodnsmstkfka.tistory.com/106)
> [염혜원] 회원가입 구현하기 2편

- lyj/2024-03-19.md
[블로그링크](https://velog.io/@yeahzzl/%EC%BD%94%EB%93%9C%EA%B0%9C%EC%84%A0%ED%95%98%EA%B8%B0)
> [이예지] 심화프로젝트 코드개선 해보기

- jms/2024-03-19.md
커리어톤 포트폴리오 제작
feat. TIL을 잘적어야 하는 이유
> [전민석] 커리어톤 포트폴리오 제작

- yhw/2024-03-20.md
- 데브캠프 참여
- 회원가입 페이지 코드 개선
- [회원가입 구현하기(3편)](https://zheldqodnsmstkfka.tistory.com/107)
> [염혜원] 회원가입 구현하기 3편

- mjh/2024-03-20.md
https://velog.io/@alswnsgur119/%EC%BF%A0%ED%82%A4%EC%99%80-%EC%84%B8%EC%85%98
> [민준혁] 쿠키와 세션, 캐시와의 차이

- jms/2024-03-20.md
https://velog.io/@minseok0920/%EB%A0%8C%EB%8D%94%EB%A7%81-%EA%B8%B0%EB%B2%95
> [전민석] 렌더링기법

- lyj/2024-03-20.md
[블로그링크](https://velog.io/@yeahzzl/Javascript-vs-Typescript-SEO%EB%9E%80)
> [이예지] 자바스크립트 vs 타입스크립트

- mjh/2024-03-21.md
https://velog.io/@alswnsgur119/JWT%EC%9D%98-%EA%B0%9C%EB%85%90-%EC%BF%A0%ED%82%A4%EC%99%80-%EC%84%B8%EC%85%98-2
> [민준혁] JWT의 개념 

- yhw/2024-03-21.md
- 데브캠프 참여
- [쿠키(Cookie)와 세션(Session)](https://zheldqodnsmstkfka.tistory.com/108)
> [염혜원] 쿠키(Cookie)와 세션(Session)

- jms/2024-03-21.md
https://velog.io/@minseok0920/%ED%95%B4%EC%8B%9C-%EB%9D%BC%EC%9A%B0%ED%8C%85
> [전민석] 해시라우팅

- mjh/2024-03-22.md
https://velog.io/@alswnsgur119/CORS
> [민준혁] CORS의 개념

- lyj/2024-03-22.md
[블로그링크](https://velog.io/@yeahzzl/%EC%9E%90%EB%B0%94%EC%8A%A4%ED%81%AC%EB%A6%BD%ED%8A%B8%EC%9D%98-%EC%9D%B4%EB%B2%A4%ED%8A%B8-%EB%A3%A8%ED%94%84Event-Loop)
(늦어서 죄송합니다ㅠ.ㅠ)
> [이예지] 자바스크립트의 이벤트루프

- phw/TIL/Mar/20240325.md
1. 자기소개서 수정
2. 포트폴리오 작성
3. 기업 지원 5곳
> [박희원] 자기소개서 및 포트폴리오 작성

- yhw/2024-03-26.md
- 데브캠프 참여
- 자소서 작성 중(자소서 왜 이리 힘들까여..😭)
- [프로그래머스 알고리즘 풀이(양꼬치)](https://zheldqodnsmstkfka.tistory.com/110)
> [염혜원] 자소서 작성 및 알고리즘 풀이

- phw/TIL/Mar/20240325.md
- phw/TIL/Mar/20240326.md
오늘 한 일
- 포트폴리오 수정 및 완성
- cs 공부
> [박희원] 기술 면접 준비 - CS 공부

- mjh/2024-03-26.md
https://velog.io/@alswnsgur119/XSS-%EC%99%80-CSRF-%EA%B3%B5%EA%B2%A9
> [민준혁] XSS와 CSRF 공격

- scs/2024-03-26.md
리액트는 특정 폴더 구조를 강제하지 않는다. 프로젝트의 규모와 복잡성에 따라 다양한 폴더 구조를 적용할 수 있다. 하지만 중요한 것은 폴더 구조의 일관성을 유지하고 팀 내에서 합의된 구조를 따르는 것이다.
잘 정의된 폴더 구조는 코드의 가독성과 유지보수성의 향상, 재사용성 및 확장성을 증가시키며 팀 내에서의 협업을 원활하게 한다. 프로젝트 초기 단계에서부터 폴더 구조에 대해 고민하고 계획하는 것이 필요한 이유이다.
```
📦 linkeeper
┣ 📂public
┣ 📂src
┃ ┣ 📂api
┃ ┣ 📂assets
┃ ┣ 📂components
┃ ┣ 📂hooks
┃ ┣ 📂layouts
┃ ┣ 📂pages
┃ ┣ 📂shared
┃ ┣ 📂styles
┃ ┗ 📂typings
```
- `api`: 서버와의 통신을 위한 API 호출 함수들
- `assets`: 이미지, 폰트, 아이콘 등과 같은 정적 자원
- `components`: 재사용 가능한 UI 컴포넌트들
- `hooks`: 커스텀 훅
- `layouts`: 헤더, 푸터, 사이드바 등의 공통 레이아웃 요소
- `pages`: 각 페이지를 구성하는 컴포넌트
- `shared`: 여러 컴포넌트나 페이지에서 공유하여 사용할 수 있는 공통 요소나 유틸리티 함수들
- `styles`: 전역 스타일, 테마, 변수 등 CSS 관련 파일
- `typings`: 타입 정의와 인터페이스 관리
리액트는 SPA이지만 페이지가 있다. React Router를 사용해 페이지를 만들기 때문에 `pages` 폴더 내의 컴포넌트를 페이지 진입점으로 사용한다. 또한 라우터 구조를 설정할 때 …
> [손창성] 프론트엔드 폴더 구조 고민

- mjh/2024-03-27.md
https://velog.io/@alswnsgur119/Proxy-%EC%84%9C%EB%B2%84
> [민준혁] proxy의 개념

- jms/2024-03-27.md
https://velog.io/@minseok0920/%EB%B8%8C%EB%9D%BC%EC%9A%B0%EC%A0%80-%EB%8F%99%EC%9E%91%EB%B0%A9%EB%B2%95
> [전민석] 브라우저

- scs/2024-03-27.md
상대 경로와 절대 경로는 파일이나 디렉토리의 위치를 나타내는 데 사용하는 경로이다. 상대 경로는 **현재 작업 중인 디렉토리를 기준으로 파일이나 디렉토리의 위치**를 나타낸다. 절대 경로는 **파일이나 디렉토리의 전체 경로**를 나타낸다. 
React 프로젝트에서 종종 다음과 같은 import 구문을 볼 수 있다.
```tsx
import SomeComponent from '../../../components/SomeComponent'
```
현재 디렉토리를 기준으로 해당 컴포넌트의 위치를 탐색하기 때문에 상대 경로가 복잡해진 것이다. 프로젝트의 규모가 커지고 폴더 구조의 깊이가 깊어질수록 `../../`와 같이 상대 경로가 길어져서 경로를 파악하기 힘들어진다. 혹여 파일이라도 옮긴다면 경로를 수정하는 것도 번거롭다.
절대 경로를 사용하면 현재 작업 중인 디렉토리와 상관없이 항상 동일한 위치를 가리킨다. 전체 경로를 나타내기 때문에 파일 및 디렉토리의 위치를 명확하게 알 수 있고, 파일의 위치가 변경되어도 상대적인 위치에 따라 import 경로를 수정할 필요가 없다.
```tsx
import SomeComponent from 'components/SomeComponent'
```
절대 경로를 사용하면 코드의 가독성과 유지보수성이 향상되는 이점이 있다.
Vite로 만든 React + TypeScript 환경에서의 절대 경로 설정 방법이다.
`compilerOptions`에 `baseUrl`과 `paths`를 추가한다. 
- `baseUrl`: 상대 경로로 모듈의 경로를 지정할 때 기준이 되는 위치
- …
> [손창성] 절대 경로 설정하기 Vite + React-TS

- mjh/2024-03-28.md
[블로그](https://velog.io/@alswnsgur119/useContext)
> [민준혁] useContext의 개념

- lyj/2024-03-28.md
- 커리어톤(면접대비 질문정리)
- 프로그래머스 알고리즘
- [블로그](https://velog.io/@yeahzzl/%ED%94%84%EB%A1%9C%EA%B7%B8%EB%9E%98%EB%A8%B8%EC%8A%A4-%EC%98%88%EC%82%B0-%EC%82%BC%EC%B4%9D%EC%82%AC)
> [이예지] 면접질문정리 & 프로그래머스

- phw/TIL/Mar/20240329.md
[블로그](https://heenee.tistory.com/169)
> [박희원] 자바스크립트 공부 (콜백지옥 / Promise)

- scs/2024-03-29.md
헤더와 사이드바, 푸터와 같은 레이아웃은 페이지마다 반복되는 UI 요소이다. 개발 과정에서 반복되는 코드는 유지보수를 어렵게 하고 코드의 가독성을 떨어뜨린다. 이렇게 반복되는 레이아웃 요소를 별도의 컴포넌트로 분리하여 다양한 페이지에서 재사용하면 코드의 중복을 줄이고 개발 효율성을 높일 수 있다.
우리가 흔히 보는 웹 사이트들을 살펴보면 디자인은 서로 달라 보여도 그 구조는 크게 다르지 않다. 
- 사이트 제목이나 로고, 검색 창이 있는(header)
- 여러 내용이 있는 본문(contents)
- 본문 외 내용을 나타내는 사이드바(sidebar)와 푸터(footer)
이를 토대로 HTML5에서는 태그 이름만 보고도 문서 구조에서 어떤 역할을 하는지 쉽게 이해할 수 있는 **'시맨틱 태그(semantic tag)'** 를 추가했다. 
> [HTML Semantic Elements](https://www.w3schools.com/html/html5_semantic_elements.asp)
레이아웃을 만들 때 시맨틱 태그를 사용하지 않더라도 레이아웃을 만들 수 있고 웹 브라우저에 나타나는 모습은 동일하다. 하지만 레이아웃을 구성할 때 시맨틱 태그를 적절히 활용하는 것은 웹 접근성과 검색 엔진 최적화(SEO)에 중요한 역할을 한다.
시각장애인들은 웹 사이트를 이용할 때 화면 낭독기 같은 웹 보조 도구를 이용하는데, 시맨틱 태그를 통해 구별할 수 있으므로 그만큼 사이트 내용을 정확히 전달할 수 있다.
또한 시맨틱 태그로 작성한 소스코드는 어느 부분이 제목이고 메뉴이고 실제 내용인지 쉽게 알 수 있다. 이렇게 …
> [손창성] React로 공통 레이아웃 구현하기

- lyj/2024-03-29.md
- 커리어톤 수료식(29일)
- 브라우저의 동작원리
- [블로그](https://velog.io/@yeahzzl/%EB%B8%8C%EB%9D%BC%EC%9A%B0%EC%A0%80%EC%9D%98-%EB%8F%99%EC%9E%91%EC%9B%90%EB%A6%AC)
> [이예지] 브라우저의 동작원리

- jms/2024-04-01,md
https://velog.io/@minseok0920/MVC-%ED%8C%A8%ED%84%B4
> [전민석] MVC 패턴

- mjh/2024-04-01.md
vite + react + typescript + supabase 로 todo만드는중 (완성되면 정리해서 공유하겠습니다!)
> [민준혁] todo하는중

- mjh/2024-04-02.md
https://velog.io/@alswnsgur119/%EC%84%A0%EC%96%B8%EC%A0%81-%ED%94%84%EB%A1%9C%EA%B7%B8%EB%9E%98%EB%B0%8D
* 벚꽃 스터디 참여
* 원티드 프리온보딩 참여
* 이력서 수정
* todo 수정중
> [민준혁] 선언적 코드

- jms/2024-04-02.md
- https://velog.io/@minseok0920/%EB%8F%99%EA%B8%B0%EC%99%80-%EB%B9%84%EB%8F%99%EA%B8%B0
- 커리어톤 챌린지 이력서 수정
- 기업지원
> [전민석] 동기와 비동기

- yhw/2024-04-02.md
오늘은 지인들과 약속이 있어 알고리즘만 풀었습니다🙇
- [프로그래머스 알고리즘 풀이(가위 바위 보)](https://zheldqodnsmstkfka.tistory.com/114)
> [염혜원] 알고리즘 풀이

- mjh/2024-04-03.md
https://velog.io/@alswnsgur119/%ED%88%AC%EB%91%90%EB%A6%AC%EC%8A%A4%ED%8A%B8-%EA%B5%AC%ED%98%84
> [민준혁] Todo완료

- yhw/2024-04-03.md
- 이력서, 자소서 수정
- [프로그래머스 알고리즘 풀이(n의 배수 고르기)](https://zheldqodnsmstkfka.tistory.com/115)
> [염혜원] 자소서, 이력서 수정

- jms/2024.04.03.md
https://velog.io/@minseok0920/%EC%83%81%ED%83%9C%EC%9D%98-%EB%B6%88%EB%B3%80%EC%84%B1
> [전민석] 상태의 불변성

- lyj/2024-04-04.md
- 벚꽃스터디 참여
- 커리어톤 챌린지 미션인증
- 문제은행 답변 ppt제작 및 녹화
- [블로그](https://velog.io/@yeahzzl/getpost)
> [이예지] 문제은행 크리에이터

- mjh/2024-04-06.md
https://velog.io/@alswnsgur119/useMemo-ugfei892
> [민준혁] useMemo

- mjh/2024-04-08.md
https://velog.io/@alswnsgur119/useRef
> [민준혁] useRef 

- jms/2024-04-08.md
https://github.com/Minseok1228/modal-context-api
> [전민석] context api로 모달만들기

- yhw/2024-04-08.md
- 기업 지원 5곳
- [프로그래머스 알고리즘 풀이(대문자와 소문자)](https://zheldqodnsmstkfka.tistory.com/116)
> [염혜원] 기업 지원 및 프로그래머스 풀이

- yhw/2024-04-09.md
- 기업 지원 3곳
- 온보딩 실시간 강의
- [프로그래머스 알고리즘 풀이(배열 두 배 만들기)](https://zheldqodnsmstkfka.tistory.com/117)
- [프로그래머스 알고리즘 풀이(중앙값 구하기)](https://zheldqodnsmstkfka.tistory.com/118)
> [염혜원] 온보딩 강의

- lyj/2024-04-09.md
- 벚꽃스터디 참여
- 커리어톤 챌린지 미션인증 + 기업지원
- 온보딩 강의
- Sass(SCSS) [블로그](https://velog.io/@yeahzzl/Sass-SCSS%EB%8A%94-%EB%AC%B4%EC%97%87%EC%9D%BC%EA%B9%8C)
> [이예지] 커리어톤챌린지, 벚꽃스터디

- lhw/2024-04-11.md
1. LeetCode 1732
```javascript 
/**
* @param {number[]} gain
* @return {number}
*/
var largestAltitude = function(gain) {
let result = [0,];
let sum = 0;
for(let i = 0; i < gain.length; i++) {
sum += gain[i];
result.push(sum);
}
return Math.max(...result)
};
```
2. RN 강의
3. React 강의
> [임홍원] 알고리즘 & 리액트강의

- mjh/2024-04-11.md
https://velog.io/@alswnsgur119/useCallback
훅에 대한 개념을 상세하게 잡고 있습니다
> [민준혁] useCallback

- jms/2024-04-11.md
> [전민석] 면접질문정리

- lhw/2024-04-12.md
1. LeetCode 724
```javascript
/**
* @param {number[]} nums
* @return {number}
*/
var pivotIndex = function(nums) {
let leftSum = 0;
let rightSum = nums.reduce((acc, cur) => acc + cur, 0);
for(let i = 0; i < nums.length; i++) {
leftSum += (nums[i - 1] || 0);
rightSum -= nums[i];
if(leftSum === rightSum) {
return i;
}
}
return -1;
};
```
2. React 강의
3. 이력서 수정
> [임홍원] 알고리즘 및 이력서 수정

- phw/TIL/Apr/20240415.md
[Algorithm][JavaScript] 프로그래머스 - 코딩테스트 입문 > 암호 해독
[블로그](https://heenee.tistory.com/172)
> [박희원] 알고리즘 풀기

- mjh/2024-04-16.md
https://velog.io/@alswnsgur119/useReducer
오늘 한것
* 최종 프로젝트 리팩토링 (폰트 최적화)
* 벚꽃 스터디 참여
* 이력서 지원동기 작성
* 기업지원
> [민준혁] useReducer의 개념과 useReducer vs Redux

- jms/2024-04-17.md
headless component를 만들어 데이터 로직과 뷰를 분리하여 투두를 만들어 봤습니다.
https://github.com/Minseok1228/todo
> [전민석] 투두로 셀프 기강잡기

- lhw/2024-04-23.md
1. LeetCode 1207
```javascript
/**
* @param {number[]} arr
* @return {boolean}
*/
var uniqueOccurrences = function(arr) {
let numMap = new Map();
let mapArr = [];
arr.map((e) => (numMap.set(e, 0)));
arr.map((e) => (
numMap.set(e, numMap.get(e) + 1)
));
mapArr = [...numMap.values()];
let numSet = new Set(mapArr);
return numSet.size < mapArr.length ? false: true;
};
```
> [임홍원] 알고리즘

- lyj/2024-04-27.md
- 커리어톤 챌린지 미션인증(기업지원, cs질문 작성 등)
- 널리소프트 코테
- React 투두, javascript 투두복습
- [블로그](https://velog.io/@yeahzzl/%EB%B0%94%EB%8B%90%EB%9D%BC-%EC%9E%90%EB%B0%94%EC%8A%A4%ED%81%AC%EB%A6%BD%ED%8A%B8%EB%A1%9C-TodoList-%EB%A7%8C%EB%93%A4%EA%B8%B0)
> [이예지] 4월 넷째주

- mjh/2024-04-18.md
- mjh/2024-04-23.md
- mjh/2024-04-26.md
- mjh/2024-04.24.md
* useId
https://velog.io/@alswnsgur119/useId
* async/await
https://velog.io/@alswnsgur119/async-await
* flux아키텍쳐
https://velog.io/@alswnsgur119/FLUX-%EC%95%84%ED%82%A4%ED%85%8D%EC%B3%90
* useLayoutEffect
https://velog.io/@alswnsgur119/useLayoutEffect
> [민준혁] 4월 넷째주

- jms/2024-04-18.md
- jms/2024-04-22.md
- jms/2024-04-24.md
- jms/2024-04-25.md
데브 캠프 진행중 입니다.
4/22 https://github.com/Minseok1228/dev-login
4/24 https://velog.io/@minseok0920/zod
4/25 https://github.com/Minseok1228/dev-auth
> [전민석] 4월 넷째주

- phw/TIL/Apr/20240422.md
- phw/TIL/Apr/20240425.md
- phw/TIL/Apr/20240427.md
- DevOps와 CI/CD 란 무엇일까? | DevOps와 CI/CD의 연관성
[https://heenee.tistory.com/174](url)
- WebSocket | WebRTC 개념, 차이점 및 등장배경
[https://heenee.tistory.com/175](url)
- 클로저(Closure)란 | 사용 예시 및 클로져 사용 이유
[https://heenee.tistory.com/176](url)
> [박희원] 4월 넷째주

- sjw/2024-05-22.md
최종프로잭트 리펙토링 진행 중 
https://github.com/jiwonson0629/nbc-puppy-ground/tree/stray-dog
middleware를 이용한 리다이렉트 정리 
https://velog.io/@juwon0629/Next.js-Middleware%EB%A5%BC-%EC%82%AC%EC%9A%A9%ED%95%98%EC%97%AC-%EC%9C%A0%EC%A0%80%EC%A0%95%EB%B3%B4-%EC%9C%A0%EB%AC%B4%EC%97%90-%EB%94%B0%EB%9D%BC-%EB%A6%AC%EB%8B%A4%EC%9D%B4%EB%A0%89%ED%8A%B8-%EC%8B%9C%ED%82%A4%EA%B8%B0
알고리즘 풀기
https://github.com/jiwonson0629/Algorithm
> [손지원] 5월 둘째주

- lyj/2024-05-18.md
여기저기서 자료조사 하면서 적은것들이라 통일성은 떨어지지만 작성한 벨로그가 없어 노션이라도 올립니다ㅠ
----
- Next.js강의(원장튜터님)
- 기술면접대비
- [노션](https://panoramic-reptile-f96.notion.site/Frontend-0f35a95884864a6b8576efde02007a7c?pvs=4)
> [이예지] 5월 셋째주

- sjw/2024-05-18.md
1. 알고리즘 풀이 :
https://github.com/jiwonson0629/Algorithm
2. 인프런 Next.js 클론코딩 강의 수강 중 :
https://github.com/jiwonson0629/z-com
> [손지원] 5월 셋째주

- jms/2024-05-15.md
- jms/2024-05-17.md
- jms/2024-05-18.md
- 클래스 컴포넌트와 함수 컴포넌트 
https://velog.io/@minseok0920/%ED%81%B4%EB%9E%98%EC%8A%A4-%EC%BB%B4%ED%8F%AC%EB%84%8C%ED%8A%B8%EC%99%80-%ED%95%A8%EC%88%98-%EC%BB%B4%ED%8F%AC%EB%84%8C%ED%8A%B8
- 리액트의 렌더링
https://velog.io/@minseok0920/%EB%A6%AC%EC%95%A1%ED%8A%B8%EC%9D%98-%EB%A0%8C%EB%8D%94%EB%A7%81
- context api를 활용한 modal
http://github.com/Minseok1228?tab=repositories
> [전민석] 5월 셋째주

- mjh/2024-05-22.md
- mjh/2024-05-24.md
- mjh/2024-05-25.md
* [SaSS 와 SCSS](https://velog.io/@alswnsgur119/SaSS-SCSS) 
*  [Recoil기초](https://velog.io/@alswnsgur119/Recoil)
* [재사용성 높은 컴포넌트 만들기(button)](https://velog.io/@alswnsgur119/%EC%9E%AC%EC%82%AC%EC%9A%A9%EC%84%B1-%EB%86%92%EC%9D%80-%EC%BB%B4%ED%8F%AC%EB%84%8C%ED%8A%B8-%EB%A7%8C%EB%93%A4%EA%B8%B0-button)
> [민준혁] 5월 넷째주

- lyj/2024-05-25.md
- 유데미 javascript강의
- 알고리즘 기초
- 기업지원
- [블로그](https://velog.io/@yeahzzl/cs-g10serc1)
> [이예지] 5월 넷째주

- sjw/2024.06.01.md
2024.05.27~31
1. 최종프로젝트 리펙토링 수정
2. Next.js 클론코딩 강의 수강 중
3. 알고리즘 풀이
4. 기업지원
> [손지원] 5월 다섯째주

- lyj/2024-06-01.md
---
- 기업지원
- 유데미 javascript강의
- 데브캠프 자료 토대로 학습시작(데브캠프 기간에 학습하지 못해서 지금 해보려고 합니다)
- [블로그](https://velog.io/@yeahzzl/shadcn-ui)
- [깃허브](https://github.com/Yeahzzl/nbc-devcamp/tree/feat/login)
> [이예지] 5월 다섯째주

- sjw/2024-06-08.md
1. Next.js 클론코딩 강의 수강중
:https://github.com/jiwonson0629/z-com/tree/home
2. 알고리즘 풀이
:https://github.com/jiwonson0629/Algorithm/tree/main/%ED%94%84%EB%A1%9C%EA%B7%B8%EB%9E%98%EB%A8%B8%EC%8A%A4/0
3. 기업지원
> [손지원] 6월 첫째주

- lyj/2024-06-08.md
---
- 기업지원
- [yarn vs npm](https://velog.io/@yeahzzl/yarn-npm-npx-%EB%AD%90%EA%B0%80-%EB%8B%A4%EB%A5%BC%EA%B9%8C)
- 데브캠프 학습 진행중
- [블로그](https://velog.io/@yeahzzl/Next%EB%A1%9C-%EB%8B%A4%ED%81%AC%EB%AA%A8%EB%93%9C-%EA%B5%AC%ED%98%84%ED%95%98%EA%B8%B0next-themes)
> [이예지] 6월 첫째주

- sjw/2024-06-22.md
1. 클론코딩 강의 수강 중
: https://github.com/jiwonson0629/z-com/tree/home 
2. 알고리즘 풀이
: https://github.com/jiwonson0629/Algorithm/tree/main/%ED%94%84%EB%A1%9C%EA%B7%B8%EB%9E%98%EB%A8%B8%EC%8A%A4/0
3. 기업지원
> [손지원] 6월 셋째주

- sjw/2024-07-06.md
1. 면접준비, 면접
2. 클론코딩 강의
https://github.com/jiwonson0629/z-com/tree/home
3. 알고리즘 풀이
https://github.com/jiwonson0629/Algorithm
> [손지원] 7월 첫째주
